databases:
  - name: hello_world
    databaseName: hello_world
    user: hello_world
    region: singapore
    plan: starter #確認用にfreeで

services:
  - type: web
    name: hello_world
    env: ruby
    region: singapore
    plan: stater #確認用にfreeで
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello_world 
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
